import React,{useEffect,useState} from 'react';
import {useParams,Link} from 'react-router-dom';
import {ExternalLink,Briefcase,MapPin,Globe,Loader2} from 'lucide-react';
import SEO from '../components/SEO';
import {fetchPublicPartner} from '../utils/api';

const PartnerPublicProfile:React.FC=()=>{
 const {slug}=useParams<{slug:string}>(); const [p,setP]=useState<any>(); const [loading,setLoading]=useState(true);
 useEffect(()=>{if(slug)fetchPublicPartner(slug).then(setP).catch(console.error).finally(()=>setLoading(false))},[slug]);
 if(loading)return <div className='min-h-screen bg-slate-950 text-white flex items-center justify-center'><Loader2 className='animate-spin mr-2'/>Loading profile...</div>;
 if(!p)return <div className='min-h-screen bg-slate-950 text-white flex items-center justify-center'>Partner not found.</div>;
 return <div className='min-h-screen bg-slate-950 text-white'><SEO title={p.display_name+' | DSH Partner'} description={p.professional_title||'Digital Solutions Hub partner profile.'}/><div className='max-w-6xl mx-auto px-5 py-10'><div className='rounded-3xl overflow-hidden border border-white/10 bg-white/5'><div className='h-48 bg-gradient-to-r from-amber-500/20 to-cyan-500/20'></div><div className='p-7 md:p-10'><div className='flex flex-col md:flex-row md:items-end gap-5 -mt-20'><div className='w-28 h-28 rounded-3xl bg-slate-900 border border-white/10 flex items-center justify-center text-3xl font-black text-amber-400 overflow-hidden'>{p.profile_photo?<img src={p.profile_photo} className='w-full h-full object-cover'/>:p.display_name?.slice(0,1)}</div><div><div className='text-xs text-amber-400 font-bold uppercase tracking-widest'>Verified DSH Partner</div><h1 className='text-3xl md:text-4xl font-black mt-1'>{p.display_name}</h1><p className='text-slate-300'>{p.professional_title}</p></div></div><div className='mt-8 grid lg:grid-cols-[1.5fr_1fr] gap-8'><div><h2 className='text-xl font-bold'>About</h2><p className='text-slate-300 mt-3 whitespace-pre-line'>{p.bio||p.portfolio?.about||'Professional digital services through Digital Solutions Hub.'}</p><div className='flex flex-wrap gap-4 mt-5 text-sm text-slate-400'>{(p.social_accounts||p.socialAccounts||[]).map((s:any)=><a key={s.id} href={s.profile_url} target='_blank' rel='noreferrer' className='text-cyan-300 hover:text-cyan-200'>{s.platform}</a>)}{p.city&&<span className='flex items-center gap-2'><MapPin className='w-4 h-4'/>{p.city}, {p.country}</span>}{p.portfolio?.website&&<a href={p.portfolio.website} target='_blank' rel='noreferrer' className='flex items-center gap-2 text-cyan-300'><Globe className='w-4 h-4'/>Website</a>}</div></div><div className='bg-slate-900 rounded-2xl p-6 border border-white/10'><h2 className='font-bold'>Services</h2><div className='mt-4 space-y-3'>{(p.services||[]).map((s:any)=><div key={s.id} className='rounded-xl bg-white/5 p-4'><div className='font-semibold'>{s.title}</div><div className='text-sm text-slate-400 mt-1'>{s.description}</div></div>)}</div></div></div><div className='mt-10'><h2 className='text-xl font-bold'>Portfolio</h2><div className='grid md:grid-cols-3 gap-4 mt-4'>{(p.portfolio_items||p.portfolioItems||[]).map((x:any)=><div key={x.id} className='rounded-2xl bg-slate-900 border border-white/10 p-5'><div className='text-xs text-amber-400'>{x.category||'Project'}</div><h3 className='font-bold mt-2'>{x.title}</h3><p className='text-sm text-slate-400 mt-2'>{x.description}</p>{x.project_url&&<a href={x.project_url} target='_blank' rel='noreferrer' className='inline-flex items-center gap-2 text-sm text-cyan-300 mt-4'>View project <ExternalLink className='w-3 h-3'/></a>}</div>)}</div></div></div></div></div></div>
}
export default PartnerPublicProfile;