import React,{useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {Loader2,Send,CheckCircle} from 'lucide-react';
import SEO from '../components/SEO';
import {submitPartnerApplication} from '../utils/api';

const PartnerApply:React.FC=()=>{
 const [form,setForm]=useState<any>({full_name:'',email:'',phone:'',country:'',city:'',bio:'',experience_years:'',availability:''});
 const [skills,setSkills]=useState(''); const [loading,setLoading]=useState(false); const [done,setDone]=useState(false); const [error,setError]=useState('');
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{await submitPartnerApplication({...form,experience_years:form.experience_years?Number(form.experience_years):null,skills:[],skills_text:skills});setDone(true)}catch(err:any){setError(err?.message||'Unable to submit application.')}finally{setLoading(false)}};
 if(done)return <div className='min-h-screen bg-slate-950 text-white flex items-center justify-center p-5'><div className='max-w-lg text-center'><CheckCircle className='w-16 h-16 text-green-400 mx-auto'/><h1 className='text-3xl font-black mt-5'>Application submitted</h1><p className='text-slate-400 mt-3'>DSH will review your application and contact you for screening/interview if shortlisted.</p></div></div>;
 return <div className='min-h-screen bg-slate-950 text-white p-5 md:p-10'><SEO title='Become a DSH Partner' description='Apply to join Digital Solutions Hub as a commission-based digital partner.'/><div className='max-w-3xl mx-auto'><div className='mb-8'><div className='text-amber-400 text-sm font-bold uppercase tracking-widest'>Digital Solutions Hub</div><h1 className='text-4xl font-black mt-2'>Become a DSH Partner</h1><p className='text-slate-400 mt-3'>Tell us about your skills. Selected applicants go through screening and interview before approval.</p></div>{error&&<div className='mb-5 bg-red-500/10 border border-red-500/20 text-red-300 rounded-xl p-4'>{error}</div>}<form onSubmit={submit} className='bg-white/5 border border-white/10 rounded-3xl p-6 md:p-8 space-y-5'><div className='grid md:grid-cols-2 gap-5'>{[['full_name','Full name'],['email','Email'],['phone','Phone'],['country','Country'],['city','City'],['experience_years','Experience years']].map(x=><label key={x[0]} className='text-sm font-semibold'>{x[1]}<input required={['full_name','email'].includes(x[0])} type={x[0]==='email'?'email':'text'} value={form[x[0]]} onChange={e=>setForm({...form,[x[0]]:e.target.value})} className='mt-2 w-full rounded-xl bg-slate-900 border border-white/10 px-4 py-3 outline-none focus:border-amber-400'/></label>)}</div><label className='text-sm font-semibold block'>Availability<input value={form.availability} onChange={e=>setForm({...form,availability:e.target.value})} placeholder='Full-time / Part-time / Project based' className='mt-2 w-full rounded-xl bg-slate-900 border border-white/10 px-4 py-3'/></label><label className='text-sm font-semibold block'>Digital skills<textarea required value={skills} onChange={e=>setSkills(e.target.value)} placeholder='e.g. SEO, Web Development, Graphic Design, AI Automation, Social Media...' className='mt-2 w-full rounded-xl bg-slate-900 border border-white/10 px-4 py-3 h-28'/></label><label className='text-sm font-semibold block'>Professional bio<textarea value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})} className='mt-2 w-full rounded-xl bg-slate-900 border border-white/10 px-4 py-3 h-32'/></label><button disabled={loading} className='w-full md:w-auto px-7 py-3 rounded-xl bg-amber-400 text-slate-950 font-black flex items-center justify-center gap-2'>{loading?<Loader2 className='animate-spin'/>:<Send className='w-4 h-4'/>}{loading?'Submitting...':'Submit application'}</button></form></div></div>
};
export default PartnerApply;