import React,{useEffect,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {LayoutDashboard,UserRound,BriefcaseBusiness,FolderKanban,Wallet,Percent,LogOut,Loader2,Save,Plus,ExternalLink} from 'lucide-react';
import SEO from '../components/SEO';
import {fetchPartnerDashboard,fetchPartnerServices,fetchPartnerCommissions,fetchPartnerWallet,logout,updatePartnerProfile,createPartnerService} from '../utils/api';

const PartnerPortal:React.FC=()=>{
 const navigate=useNavigate(); const [data,setData]=useState<any>(); const [services,setServices]=useState<any[]>([]); const [commissions,setCommissions]=useState<any>(); const [wallet,setWallet]=useState<any>(); const [view,setView]=useState('overview'); const [loading,setLoading]=useState(true); const [profile,setProfile]=useState<any>({}); const [saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await Promise.all([fetchPartnerDashboard(),fetchPartnerServices(),fetchPartnerCommissions(),fetchPartnerWallet()]);setData(r[0]);setServices(r[1]);setCommissions(r[2]);setWallet(r[3]);setProfile(r[0].partner||{});}catch(e){console.error(e)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 if(loading)return <div className='min-h-screen bg-slate-950 text-white flex items-center justify-center'><Loader2 className='animate-spin mr-2'/>Loading partner portal...</div>;
 if(!data?.partner)return <div className='min-h-screen bg-slate-950 text-white flex items-center justify-center'>Partner profile not found.</div>;
 const p=data.partner;
 const nav:any[]=[['overview','Overview',LayoutDashboard],['profile','Profile',UserRound],['services','Services',BriefcaseBusiness],['orders','Projects & Orders',FolderKanban],['commissions','Commissions',Percent],['wallet','Wallet & Payouts',Wallet]];
 const save=async()=>{setSaving(true);try{const x=await updatePartnerProfile(profile);setProfile(x);setData({...data,partner:x})}finally{setSaving(false)}};
 return <div className='min-h-screen bg-slate-100 text-slate-900 flex'><SEO title='DSH Partner Portal' description='Manage your DSH partner profile, services and commissions.'/><aside className='w-72 bg-slate-950 text-white fixed inset-y-0 left-0 z-20 hidden lg:flex flex-col'><div className='p-6 border-b border-white/10'><div className='text-xl font-black'>DSH <span className='text-amber-400'>PARTNER</span></div><p className='text-xs text-slate-400 mt-1'>{p.partner_code}</p></div><nav className='p-4 space-y-1 flex-1'>{nav.map(([k,l,I])=><button key={k} onClick={()=>setView(k)} className={'w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm '+(view===k?'bg-amber-400 text-slate-950 font-bold':'text-slate-300 hover:bg-white/5')}><I className='w-5 h-5'/>{l}</button>)}</nav><div className='p-4 border-t border-white/10'><Link to={'/p/'+p.slug} target='_blank' className='flex items-center gap-2 text-sm text-slate-300 mb-4'><ExternalLink className='w-4 h-4'/>Public profile</Link><button onClick={async()=>{await logout();navigate('/en/login')}} className='flex items-center gap-2 text-sm text-red-300'><LogOut className='w-4 h-4'/>Sign out</button></div></aside>
 <main className='flex-1 lg:ml-72 p-5 md:p-8'><header className='mb-8'><p className='text-sm text-slate-500'>Digital Solutions Hub</p><h1 className='text-3xl font-black mt-1'>{view==='overview'?'Partner Dashboard':(nav.find(x=>x[0]===view)?.[1]||'Partner')}</h1></header>
 {view==='overview'&&<div className='space-y-6'><div className='grid sm:grid-cols-2 xl:grid-cols-4 gap-4'>{[['Active Services',data.stats.activeServices],['Active Orders',data.stats.activeOrders],['Total Earned','$'+Number(data.stats.totalEarned).toFixed(2)],['Available Balance','$'+Number(data.stats.availableBalance).toFixed(2)]].map(x=><div key={String(x[0])} className='bg-white rounded-2xl border p-5'><p className='text-xs uppercase text-slate-500'>{x[0]}</p><p className='text-2xl font-black mt-2'>{x[1]}</p></div>)}</div><div className='bg-white rounded-2xl border p-6'><h2 className='font-bold mb-4'>Recent Orders</h2><div className='space-y-3'>{data.recentOrders.map((o:any)=><div key={o.id} className='border rounded-xl p-4 flex flex-wrap justify-between gap-2'><b>{o.order_number}</b><span>{o.currency} {o.total}</span><span>{o.payment_status}</span><span>{o.status}</span></div>)}</div></div></div>}
 {view==='profile'&&<div className='bg-white rounded-2xl border p-6 max-w-4xl space-y-5'><div className='grid md:grid-cols-2 gap-5'>{[['display_name','Display name'],['professional_title','Professional title'],['country','Country'],['city','City'],['timezone','Timezone']].map(x=><label key={x[0]} className='text-sm font-semibold'>{x[1]}<input value={profile[x[0]]||''} onChange={e=>setProfile({...profile,[x[0]]:e.target.value})} className='mt-2 w-full rounded-xl border px-4 py-3'/></label>)}<label className='md:col-span-2 text-sm font-semibold'>Bio<textarea value={profile.bio||''} onChange={e=>setProfile({...profile,bio:e.target.value})} className='mt-2 w-full rounded-xl border px-4 py-3 h-32'/></label></div><button onClick={save} disabled={saving} className='px-5 py-3 rounded-xl bg-slate-950 text-white font-bold flex items-center gap-2'><Save className='w-4 h-4'/>{saving?'Saving...':'Save profile'}</button></div>}
 {view==='services'&&<div className='bg-white rounded-2xl border p-6'><h2 className='font-bold text-lg'>Your services</h2><p className='text-sm text-slate-500 mt-2'>Services are managed from this partner workspace. DSH controls client billing and per-order commission.</p><div className='mt-5 space-y-3'>{services.map((s:any)=><div key={s.id} className='border rounded-xl p-4'><b>{s.title}</b><p className='text-sm text-slate-500'>{s.description||'No description'}</p><p className='text-sm mt-2'>{s.pricing_type} {s.starting_price?'• '+s.currency+' '+s.starting_price:''}</p></div>)}</div></div>}
 {view==='orders'&&<div className='bg-white rounded-2xl border p-6'><h2 className='font-bold'>Projects & Orders</h2><p className='text-sm text-slate-500 mt-2'>Client payments are received by DSH first. Internal commission splits are not shown to clients.</p><div className='mt-5 space-y-3'>{data.recentOrders.map((o:any)=><div key={o.id} className='border rounded-xl p-4'><b>{o.order_number}</b><div className='text-sm text-slate-500'>{o.title}</div><div className='mt-2 font-semibold'>{o.currency} {o.total}</div></div>)}</div></div>}
 {view==='commissions'&&<div className='bg-white rounded-2xl border p-6'><h2 className='font-bold'>Commission ledger</h2><p className='text-sm text-slate-500 mt-2 mb-5'>Each order has an admin-approved, locked commission.</p><div className='space-y-3'>{(commissions?.data||[]).map((c:any)=><div key={c.id} className='border rounded-xl p-4 grid sm:grid-cols-4 gap-2'><span>Order #{c.order_id}</span><span>Gross {c.currency} {c.gross_amount}</span><span>Partner {c.currency} {c.partner_amount}</span><span>Status {c.status}</span></div>)}</div></div>}
 {view==='wallet'&&<div className='space-y-5'><div className='grid md:grid-cols-3 gap-4'>{[['Pending',wallet?.wallet?.pending_balance],['Available',wallet?.wallet?.available_balance],['Paid',wallet?.wallet?.paid_balance]].map(x=><div key={String(x[0])} className='bg-white rounded-2xl border p-5'><p className='text-xs text-slate-500'>{x[0]}</p><p className='text-2xl font-black mt-2'>$'+Number(x[1]||0).toFixed(2)+'</p></div>)}</div></div>}
 </main></div>;
};
export default PartnerPortal;